- hosts: localhost
  connection: local
  become: true

  tasks:
    - include: tasks/packages.yml
    - include: tasks/starship.yml

    - name: copy .bashrc to home directory
      copy:
        src: dotfiles/bashrc
        dest: $HOME
        owner: eb
        owner: eb
