- hosts: localhost
  connection: local
  become: true

  tasks:
    - include: tasks/packages.yml
    - include: tasks/starship.yml

    - name: copy .bashrc to home directory
      copy:
        src: dotfiles/bashrc
        dest: /home/eb/.bashrc
        owner: eb
        owner: eb

    - name: copy gitconfig to home directory
      copy:
        src: dotfiles/gitconfig
        dest: /home/eb/.gitconfig
        owner: eb
        owner: eb

    - name: copy starship.toml to config directory
      copy:
        src: dotfiles/starship
        dest: /home/eb/.config/starship/starship.toml
        owner: eb
        owner: eb

    - name: copy init.vim to config directory
      copy:
        src: dotfiles/init.vim
        dest: /home/eb/.config/nvim/init.vim
        owner: eb
        owner: eb
