- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False
    
    - name: add ssh keys for ansible
      authorized_key:
        user: eb
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExEosYvNYgwV7M3r2ho2o+Hbq2B2FPHSaq2+ixEpesB ansible"

    - name: add ssh keys for ebuntu
      authorized_key:
        user: eb
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGlLyWGGAD+jPIap+hCSvDhVyfxO/X3sk+SuTuZG4PKJ ebuntu default"

  tasks:
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/pfetch.yml
    - include: tasks/user.yml
    - include: tasks/cron.yml

