- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/starship.yml

    - name: copy .bashrc to home directory
      copy:
        src: files/bashrc
        dest: $HOME
        owner: $USER
        owner: $USER
