---

- hosts: localhost
  connection: local
  become: true

  vars_files: vars/vars.yml

  pre_tasks:
    - include: tasks/ssh.yml

  tasks:
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/tmux_utils.yml
    - include: tasks/pfetch.yml
    - include: tasks/user.yml
    - include: tasks/cron.yml
