- hosts: localhost
  connection: local
  become: true

  vars_files: vars/vars.yml

  pre_tasks:
    - name: Update repositories for Ubuntu.
      apt:
        update_cache: yes
      changed_when: False
      when: ansible_distribution == "Ubuntu"

    - name: Add ssh keys for ansible.
      authorized_key:
        user: "{{ user }}"
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExEosYvNYgwV7M3r2ho2o+Hbq2B2FPHSaq2+ixEpesB ansible"

    - name: Add ssh keys for ebuntu.
      authorized_key:
        user: "{{ user }}"
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGlLyWGGAD+jPIap+hCSvDhVyfxO/X3sk+SuTuZG4PKJ ebuntu default"

    - name: Add ssh keys for t490.
      authorized_key:
        user: "{{ user }}"
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAwOSl1vMCxFVbKpAi43keALKFlP4CWxmstZ3EOSUPWk eb-t490"

    - name: Add ssh keys for t490.
      authorized_key:
        user: "{{ user }}"
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAQ2jRVJo4ZoKJb6DSA3SNlsjFd5pdPIGE02kVNNPzsN ansible-t490"

  tasks:
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
      #    - include: tasks/starship.yml
    - include: tasks/pfetch.yml
    - include: tasks/user.yml
    - include: tasks/cron.yml

