---

- name: Create directories.
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - .config/starship
    - .config/nvim/nvim_plug/plugged
    - .bashtools

- name: Copy configuration files.
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - src: dotfiles/bashrc
      dest: "/home/{{ user }}/.bashrc"
    - src: dotfiles/tmux.conf
      dest: "/home/{{ user }}/.tmux.conf"
    - src: dotfiles/gitconfig
      dest: "/home/{{ user }}/.gitconfig"
    - src: dotfiles/starship
      dest: "/home/{{ user }}/.config/starship/starship.toml"
    - src: dotfiles/init.vim
      dest: "/home/{{ user }}/.config/nvim/init.vim"
    - src: dotfiles/fzf-bash-completions
      dest: "/home/{{ user }}/.bashtools/fzf-bash-completion.sh"
