---

- name: clone my nvim configs from github
  ansible.builtin.git:
    repo: https://github.com/eb0687/nvim.git
    dest: "/home/{{ user }}/.config/nvim"
    version: main
  become: true
  become_user: "{{ user }}"
