---

- name: Install packages.
  apt:
    name:
      - htop
      - tmux
      - fzf
      - fd-find
      - tree
      - bat
      - python3-pip

- name: Install neovim from releases page.
  apt:
    deb: "https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim-linux64.deb"

