- name: Download pfetch.
  get_url:
    url: "https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch"
    dest: "{{ download_dir }}/pfetch"

- name: Move pfetch to path.
  copy:
    src: "{{ download_dir }}/pfetch"
    dest: /usr/local/bin/pfetch
    owner: root
    group: root
    mode: 0755
