- name: download pfetch
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch"
    dest: /tmp/pfetch

- name: move pfetch to path
  ansible.builtin.copy:
    src: /tmp/pfetch
    dest: /usr/local/bin/pfetch
    owner: root
    group: root
    mode: 0755
