- name: Download starship
  ansible.builtin.get_url:
    url: curl -sS https://starship.rs/install.sh
    dest: /tmp/starship_install.sh

- name: Install starship
  ansible.builtin.shell:
    cmd: cat /tmp/starship_install.sh | sh -s -- -y
