---

- name: Download Starship.
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: "{{ download_dir }}/starship_install.sh"

- name: Install Starship.
  ansible.builtin.shell:
    cmd: cat "{{ download_dir }}/starship_install.sh" | sh -s -- -y
