---

- name: Copy TMUX utilities to local bin directory.
  become: false
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  with_items:
    - src: files/local/bin/
      dest: "/home/{{ user }}/.local/bin/"
