---

- name: Add ansible user.
  user:
    name: ansible
    system: true

- name: Set up sudo for ansible user.
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
